Dlr: 0.0001
Glr: 0.0001
analogy_scale: 0.3
attr: 1@2@3@4@5@6@7
attr_names:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
aug_param:
  crop_param:
    size:
    - 170
    - 170
  resize_param:
    ratio_h:
    - 0.8
    - 1.2
    ratio_w:
    - 0.8
    - 1.2
    version: v2
  rotation_param:
    degrees:
    - -10
    - 10
  shift_param:
    bias:
    - 5
    - 5
basemodel: rafd
basemodel_version: v4
batch_size: 16
cls_type: CE
continue_train: false
csv_path: info/Rafd_image.csv
disc_type: multiScale
discrim:
  image_size: 128
  n_scale: 3
  norm: none
  repeat_num: 6
dst_attr: 4
dst_aug: True
dst_aug_param:
  crop_param:
    size:
    - 90
    - 100
  resize_param:
    ratio_h:
    - 0.8
    - 1.2
    ratio_w:
    - 0.8
    - 1.2
    version: v2
  rotation_param:
    degrees:
    - -10
    - 10
  shift_param:
    bias:
    - 5
    - 5
dst_crop_size1: 90
dst_crop_size2: 100
dst_dir1: datasets/sketch_dataset/train
dst_dir2: datasets/painting_dataset/train
epoch: 5000
framework_config:
  n_save_img: 100
  num_workers: 8
g_type: adain
ganloss: LSGANLoss_multiScale
generator:
  act_type: lrelu
  c_dim: 0
  condition: true
  conv_dim: 128
  n_down: 1
  repeat_num: 4
lam_cls: 10
lam_recon: 50
lam_recon_per: 1
lam_vgg: 10
lam_gan: 1
n_dis: 1
optimizer: basic
recon_type: BAB
save_dir: checkpoints/view_synthesis
src_aug: True
src_crop_size:
- 170
- 170
src_data_dir: datasets/pie
src_train_list: info/view_synthesis.txt
vgg_layers:
- 1
- 2
